### ISSUE TITLE
ESP32-C6 support with Arduino-ESP 3.0.0?

### ISSUE THREAD

**Issue by derbirch** [ph1p/ikea-led-obegraensad#113]
I'm totally new to ESP dev and PlatformIO. With basic knowledge in C, I tried to twist some fun to meet the new Arduino 3 & ESP IDF 5.1 API changes, but the SDK still seems to be a big issue when I try to build.

Is there any suggested `platform.ini` config for the `esp32-c6-devkitc-1` board? Or do I have to pick other esp32 boards? If so, do you have any recommendations? I struggle to pick esp32 boards as there are too many SoC models/variations and different boards with them.

Thx in advance.

**Comment by BrookeDot** [comment]
Hi @derbirch I recently built another PlatformIO project (ESPHome) on the ESP32-C6 and I'll admit it was not very straight forward, if you are new to the ESP I may recommend a board that has been around for a while[. The Readme has a few recommendations](https://github.com/ph1p/ikea-led-obegraensad?tab=readme-ov-file#pins), I just updated my NodeMCU and noticed that the 4MB is getting filled, so you may want to go with an 8MB board if you have the budget.

Beyond that, I would recommend sticking with the ESP32 over the 8266 due to the increased RAM, you'll just have a better time :-) So that would leave you with the Lolin D32 (Pro), which I haven't used, but looks like a nice board.

If it's helpful, here is the ESPHome config (they use YAML) that did end up compiling:
```
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
```
